-- Migration: Insert sample events
-- Date: 2024-01-01

-- Insert sample events (assuming admin user with id=1 exists)
INSERT IGNORE INTO events (
    title, 
    description, 
    short_description, 
    category_id, 
    organizer_id, 
    event_date, 
    event_time, 
    end_date, 
    end_time, 
    location, 
    address, 
    city, 
    province, 
    max_participants, 
    price, 
    is_free, 
    status, 
    is_featured
) VALUES
(
    'Tech Conference 2024', 
    'Join us for the biggest technology conference of the year featuring industry leaders, innovative startups, and cutting-edge technologies. Learn about AI, blockchain, cloud computing, and the future of technology.',
    'The biggest technology conference featuring AI, blockchain, and cloud computing innovations.',
    1, 
    1, 
    '2024-03-15', 
    '09:00:00', 
    '2024-03-15', 
    '17:00:00', 
    'Jakarta Convention Center', 
    'Jl. Gatot Subroto, Senayan', 
    'Jakarta', 
    'DKI Jakarta', 
    500, 
    250000.00, 
    FALSE, 
    'published', 
    TRUE
),
(
    'Digital Marketing Workshop', 
    'Learn the latest digital marketing strategies including social media marketing, SEO, content marketing, and paid advertising. Perfect for business owners and marketing professionals.',
    'Master digital marketing strategies including SEO, social media, and content marketing.',
    2, 
    1, 
    '2024-03-20', 
    '10:00:00', 
    '2024-03-20', 
    '16:00:00', 
    'Bandung Creative Hub', 
    'Jl. Layang-Layang No. 8', 
    'Bandung', 
    'Jawa Barat', 
    100, 
    150000.00, 
    FALSE, 
    'published', 
    FALSE
),
(
    'Programming Bootcamp', 
    'Intensive 3-day programming bootcamp covering web development fundamentals including HTML, CSS, JavaScript, React, and Node.js. Hands-on projects and mentorship included.',
    'Intensive 3-day web development bootcamp with React and Node.js.',
    3, 
    1, 
    '2024-03-25', 
    '09:00:00', 
    '2024-03-27', 
    '17:00:00', 
    'Surabaya Tech Park', 
    'Jl. Raya ITS, Keputih', 
    'Surabaya', 
    'Jawa Timur', 
    50, 
    500000.00, 
    FALSE, 
    'published', 
    TRUE
),
(
    'Music Festival Yogyakarta', 
    'Experience the best of Indonesian and international music at this 2-day festival featuring rock, pop, jazz, and traditional music performances in the cultural heart of Indonesia.',
    'Two-day music festival featuring rock, pop, jazz, and traditional performances.',
    4, 
    1, 
    '2024-04-05', 
    '16:00:00', 
    '2024-04-06', 
    '23:00:00', 
    'Taman Budaya Yogyakarta', 
    'Jl. Sriwedani No. 1', 
    'Yogyakarta', 
    'DI Yogyakarta', 
    2000, 
    75000.00, 
    FALSE, 
    'published', 
    TRUE
),
(
    'Marathon Bali 2024', 
    'Join thousands of runners in this scenic marathon through beautiful Bali landscapes. Categories include full marathon, half marathon, and 10K fun run for all fitness levels.',
    'Scenic marathon through beautiful Bali with multiple distance categories.',
    5, 
    1, 
    '2024-04-10', 
    '06:00:00', 
    '2024-04-10', 
    '12:00:00', 
    'Sanur Beach', 
    'Pantai Sanur, Denpasar Selatan', 
    'Denpasar', 
    'Bali', 
    3000, 
    200000.00, 
    FALSE, 
    'published', 
    FALSE
),
(
    'Health & Wellness Seminar', 
    'Learn about nutrition, mental health, fitness, and preventive healthcare from medical experts and wellness coaches. Includes free health screenings and wellness consultations.',
    'Comprehensive health seminar with expert speakers and free health screenings.',
    6, 
    1, 
    '2024-04-15', 
    '08:00:00', 
    '2024-04-15', 
    '15:00:00', 
    'Medan Convention Hall', 
    'Jl. Gagak Hitam No. 1', 
    'Medan', 
    'Sumatera Utara', 
    300, 
    0.00, 
    TRUE, 
    'published', 
    FALSE
),
(
    'Community Cleanup Day', 
    'Join your local community in making our city cleaner and greener. Volunteer activities include beach cleanup, tree planting, and environmental education. All ages welcome!',
    'Community volunteer event for environmental cleanup and tree planting.',
    7, 
    1, 
    '2024-04-20', 
    '07:00:00', 
    '2024-04-20', 
    '12:00:00', 
    'Ancol Beach', 
    'Jl. Lodan Timur No. 7', 
    'Jakarta', 
    'DKI Jakarta', 
    200, 
    0.00, 
    TRUE, 
    'published', 
    FALSE
),
(
    'Culinary Festival Makassar', 
    'Taste the best of Indonesian cuisine at this food festival featuring traditional dishes, modern fusion, cooking demonstrations, and food competitions from renowned chefs.',
    'Indonesian culinary festival with traditional dishes and cooking demonstrations.',
    8, 
    1, 
    '2024-04-25', 
    '11:00:00', 
    '2024-04-25', 
    '21:00:00', 
    'Fort Rotterdam', 
    'Jl. Ujung Pandang', 
    'Makassar', 
    'Sulawesi Selatan', 
    1000, 
    50000.00, 
    FALSE, 
    'published', 
    TRUE
),
(
    'Startup Pitch Competition', 
    'Entrepreneurs showcase their innovative business ideas to investors and industry experts. Network with fellow entrepreneurs, learn from successful founders, and compete for funding.',
    'Startup competition with investor pitches and networking opportunities.',
    2, 
    1, 
    '2024-05-01', 
    '13:00:00', 
    '2024-05-01', 
    '18:00:00', 
    'Semarang Business Center', 
    'Jl. Pemuda No. 142', 
    'Semarang', 
    'Jawa Tengah', 
    150, 
    100000.00, 
    FALSE, 
    'published', 
    FALSE
),
(
    'Art Exhibition Opening', 
    'Contemporary art exhibition featuring works by emerging Indonesian artists. Explore paintings, sculptures, digital art, and interactive installations in this cultural celebration.',
    'Contemporary art exhibition featuring emerging Indonesian artists.',
    4, 
    1, 
    '2024-05-05', 
    '19:00:00', 
    '2024-05-05', 
    '22:00:00', 
    'National Gallery', 
    'Jl. Medan Merdeka Timur No. 14', 
    'Jakarta', 
    'DKI Jakarta', 
    250, 
    0.00, 
    TRUE, 
    'published', 
    FALSE
);
